// Conformance against the golden corpus generated by rustychickpeas-format
// (the source of truth for the frozen RCPG v1 byte layout). Three claims per
// positive file: it parses to the manifest's facts; re-encoding the parsed
// graph reproduces the original bytes; and rebuilding the same logical graph
// from scratch with this module's builders also reproduces them. Negative
// files must fail with the declared error class, never panic.

package rcpg_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/freeeve/gochickpeas/rcpg"
	"github.com/freeeve/gochickpeas/rcpg/internal/conformance"
)

const corpusDir = "testdata/conformance"

type manifest struct {
	FormatVersion int            `json:"format_version"`
	Files         []manifestFile `json:"files"`
}

type manifestFile struct {
	Name         string     `json:"name"`
	Expect       string     `json:"expect"`
	NNodes       uint32     `json:"n_nodes"`
	NRels        uint64     `json:"n_rels"`
	CSRIDSpace   uint32     `json:"csr_id_space"`
	NAtoms       int        `json:"n_atoms"`
	Version      *string    `json:"version"`
	NLabels      int        `json:"n_labels"`
	NTypes       int        `json:"n_types"`
	NNodeColumns int        `json:"n_node_columns"`
	NRelColumns  int        `json:"n_rel_columns"`
	AdjChecks    []adjCheck `json:"adj_checks"`
	ColChecks    []colCheck `json:"col_checks"`
}

type adjCheck struct {
	Node uint32   `json:"node"`
	Out  []uint32 `json:"out"`
	In   []uint32 `json:"in"`
}

type colCheck struct {
	Scope   string `json:"scope"`
	KeyAtom uint32 `json:"key_atom"`
	Pos     uint32 `json:"pos"`
	Value   string `json:"value"`
}

func loadManifest(t *testing.T) manifest {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(corpusDir, "manifest.json"))
	if err != nil {
		t.Fatalf("reading manifest: %v", err)
	}
	var m manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("decoding manifest: %v", err)
	}
	if m.FormatVersion != int(rcpg.Version) {
		t.Fatalf("manifest format_version %d, this package supports %d", m.FormatVersion, rcpg.Version)
	}
	return m
}

func readCorpusFile(t *testing.T, name string) []byte {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(corpusDir, name))
	if err != nil {
		t.Fatalf("reading corpus file: %v", err)
	}
	return raw
}

func TestCorpusParsesToManifestFacts(t *testing.T) {
	for _, f := range loadManifest(t).Files {
		if f.Expect != "ok" {
			continue
		}
		t.Run(f.Name, func(t *testing.T) {
			g, err := rcpg.Parse(readCorpusFile(t, f.Name))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			assertFacts(t, g, f)
		})
	}
}

func assertFacts(t *testing.T, g *rcpg.GraphSection, f manifestFile) {
	t.Helper()
	if g.NNodes != f.NNodes || g.NRels != f.NRels || g.CSRIDSpace() != f.CSRIDSpace {
		t.Errorf("counts: got nodes=%d rels=%d space=%d, want %d/%d/%d",
			g.NNodes, g.NRels, g.CSRIDSpace(), f.NNodes, f.NRels, f.CSRIDSpace)
	}
	if len(g.Atoms) != f.NAtoms {
		t.Errorf("atoms: got %d, want %d", len(g.Atoms), f.NAtoms)
	}
	if !versionEqual(g.Version, f.Version) {
		t.Errorf("version: got %v, want %v", g.Version, f.Version)
	}
	if len(g.LabelIndex) != f.NLabels || len(g.TypeIndex) != f.NTypes {
		t.Errorf("indexes: got %d labels / %d types, want %d/%d",
			len(g.LabelIndex), len(g.TypeIndex), f.NLabels, f.NTypes)
	}
	if len(g.NodeColumns) != f.NNodeColumns || len(g.RelColumns) != f.NRelColumns {
		t.Errorf("columns: got %d node / %d rel, want %d/%d",
			len(g.NodeColumns), len(g.RelColumns), f.NNodeColumns, f.NRelColumns)
	}
	for _, c := range f.AdjChecks {
		if got := g.OutNeighbors(c.Node); !u32sEqual(got, c.Out) {
			t.Errorf("node %d out: got %v, want %v", c.Node, got, c.Out)
		}
		if got := g.InNeighbors(c.Node); !u32sEqual(got, c.In) {
			t.Errorf("node %d in: got %v, want %v", c.Node, got, c.In)
		}
	}
	for _, c := range f.ColChecks {
		cols := g.NodeColumns
		if c.Scope == "rel" {
			cols = g.RelColumns
		}
		got := "missing column"
		for _, col := range cols {
			if col.Key == c.KeyAtom {
				got = columnValueAt(col.Data, c.Pos)
				break
			}
		}
		if got != c.Value {
			t.Errorf("%s column %d pos %d: got %q, want %q", c.Scope, c.KeyAtom, c.Pos, got, c.Value)
		}
	}
}

// columnValueAt renders the value at pos in the manifest's tagged-string
// encoding ("i64:..", "f64bits:..", "bool:..", "str:<atom>", "absent").
func columnValueAt(data rcpg.ColumnData, pos uint32) string {
	switch d := data.(type) {
	case rcpg.DenseI64:
		return fmt.Sprintf("i64:%d", d[pos])
	case rcpg.DenseF64:
		return fmt.Sprintf("f64bits:%d", math.Float64bits(d[pos]))
	case rcpg.DenseBool:
		return fmt.Sprintf("bool:%t", d.Get(pos))
	case rcpg.DenseStr:
		return fmt.Sprintf("str:%d", d[pos])
	case rcpg.SparseI64:
		for _, e := range d {
			if e.ID == pos {
				return fmt.Sprintf("i64:%d", e.Val)
			}
		}
	case rcpg.SparseF64:
		for _, e := range d {
			if e.ID == pos {
				return fmt.Sprintf("f64bits:%d", math.Float64bits(e.Val))
			}
		}
	case rcpg.SparseBool:
		for _, e := range d {
			if e.ID == pos {
				return fmt.Sprintf("bool:%t", e.Val)
			}
		}
	case rcpg.SparseStr:
		for _, e := range d {
			if e.ID == pos {
				return fmt.Sprintf("str:%d", e.Val)
			}
		}
	}
	return "absent"
}

// TestCorpusRewriteIsByteIdentical re-encodes each parsed golden file with
// the section set the original carried and requires byte equality -- the
// Rust and Go writers must be indistinguishable. Files carrying an unknown
// section are checked semantically instead (a writer never re-emits sections
// it does not understand).
func TestCorpusRewriteIsByteIdentical(t *testing.T) {
	for _, f := range loadManifest(t).Files {
		if f.Expect != "ok" {
			continue
		}
		t.Run(f.Name, func(t *testing.T) {
			raw := readCorpusFile(t, f.Name)
			g, err := rcpg.Parse(raw)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			dir, err := rcpg.ParseDirectory(raw)
			if err != nil {
				t.Fatalf("directory: %v", err)
			}
			opts := rcpg.TopologyOnlyWriteOptions()
			unknown := false
			for _, e := range dir.Entries() {
				switch e.ID {
				case 5:
					opts.NodeColumns = true
				case 6:
					opts.RelColumns = true
				case 7:
					opts.AtomIndex = true
				case 1, 2, 3, 4:
				default:
					unknown = true
				}
			}
			var buf bytes.Buffer
			if err := rcpg.WriteWith(g, &buf, opts); err != nil {
				t.Fatalf("rewrite: %v", err)
			}
			if unknown {
				reparsed, err := rcpg.Parse(buf.Bytes())
				if err != nil {
					t.Fatalf("reparse: %v", err)
				}
				if !graphsEqual(g, reparsed) {
					t.Fatal("rewrite of unknown-section file lost data")
				}
				return
			}
			if !bytes.Equal(raw, buf.Bytes()) {
				t.Fatalf("rewrite differs from golden bytes (got %d bytes, want %d)",
					buf.Len(), len(raw))
			}
		})
	}
}

// TestGoBuiltCorpusMatchesVendored rebuilds every logical corpus graph from
// scratch with this module's builders and requires the encoding to equal the
// Rust-written golden bytes -- proving from-scratch Go construction (across
// array, bitmap, and run roaring containers) is byte-compatible, not merely
// parse-compatible.
func TestGoBuiltCorpusMatchesVendored(t *testing.T) {
	for _, c := range conformance.Corpus() {
		t.Run(c.Name, func(t *testing.T) {
			got, err := conformance.EncodeCase(c)
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			want := readCorpusFile(t, c.Name+".rcpg")
			if !bytes.Equal(got, want) {
				t.Fatalf("Go-built encoding differs from golden bytes (got %d bytes, want %d): %s",
					len(got), len(want), firstDiff(got, want))
			}
		})
	}
}

// firstDiff describes the first differing offset with hex context, for
// pinpointing which section drifted.
func firstDiff(got, want []byte) string {
	n := min(len(got), len(want))
	for i := range n {
		if got[i] != want[i] {
			lo := max(i-8, 0)
			hi := min(i+8, n)
			return fmt.Sprintf("first diff at offset %d: got ..%x.., want ..%x..",
				i, got[lo:hi], want[lo:hi])
		}
	}
	return fmt.Sprintf("common prefix of %d bytes, lengths differ", n)
}

func TestNegativeCorpusFailsWithTypedErrors(t *testing.T) {
	for _, f := range loadManifest(t).Files {
		if f.Expect == "ok" {
			continue
		}
		t.Run(f.Name, func(t *testing.T) {
			_, err := rcpg.Parse(readCorpusFile(t, f.Name))
			if err == nil {
				t.Fatal("parse of corrupt file succeeded")
			}
			want := rcpg.ErrCorrupt
			if f.Expect == "unsupported_version" {
				want = rcpg.ErrUnsupportedVersion
			}
			if !errors.Is(err, want) {
				t.Fatalf("got error %v, want %v", err, want)
			}
		})
	}
}

// TestManifestCoversAllCorpusFiles keeps the vendored directory and the
// manifest in lockstep: every .rcpg present is claimed, and vice versa.
func TestManifestCoversAllCorpusFiles(t *testing.T) {
	claimed := map[string]bool{}
	for _, f := range loadManifest(t).Files {
		claimed[f.Name] = true
	}
	entries, err := os.ReadDir(corpusDir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".rcpg") {
			continue
		}
		if !claimed[e.Name()] {
			t.Errorf("corpus file %s not in manifest", e.Name())
		}
		delete(claimed, e.Name())
	}
	for name := range claimed {
		t.Errorf("manifest claims missing file %s", name)
	}
}
