#!/usr/bin/env bash
# Regenerate PARITY.md: one row per public function in rustychickpeas-core,
# preserving the go symbol / status / notes columns of existing rows so the
# checklist survives regeneration as the Rust side keeps moving.
#
# Usage: scripts/parity.sh [path-to-rustychickpeas]   (default: ../rustychickpeas)
set -euo pipefail

rust_repo="${1:-../rustychickpeas}"
core="$rust_repo/rustychickpeas-core/src"
out="PARITY.md"

if [[ ! -d "$core" ]]; then
  echo "rustychickpeas-core not found at $core" >&2
  exit 1
fi

tmp_symbols=$(mktemp)
tmp_prev=$(mktemp)
tmp_out=$(mktemp)
trap 'rm -f "$tmp_symbols" "$tmp_prev" "$tmp_out"' EXIT

# "file|symbol" pairs for every pub fn outside test code.
grep -rn --include='*.rs' -E '^\s*pub (async )?fn [a-z_0-9]+' "$core" \
  | grep -v '/tests\.rs' \
  | sed -E "s|^$core/||; s|:[0-9]+:[[:space:]]*pub (async )?fn ([a-z_0-9]+).*|\|\2|" \
  | sort -u > "$tmp_symbols"

if [[ -f "$out" ]]; then
  cp "$out" "$tmp_prev"
fi

{
  echo "# Parity checklist"
  echo
  echo "Generated by scripts/parity.sh from rustychickpeas-core's public functions."
  echo "Statuses: todo / done / wontport (with a reason in notes)."
  echo
  echo "| file | rust symbol | go symbol | status | notes |"
  echo "|------|-------------|-----------|--------|-------|"
  # Two-input awk: the previous checklist first (indexing rows by
  # "file|symbol" so filled columns survive), then the fresh symbol list.
  awk -F'|' '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    FNR == NR {
      if ($0 !~ /^\|/) next
      file = trim($2); sym = trim($3)
      if (file == "file" || file ~ /^-+$/ || file == "") next
      kept[file "|" sym] = $0
      next
    }
    {
      file = trim($1); sym = trim($2)
      key = file "|" sym
      if (key in kept) print kept[key]
      else printf "| %s | %s | | todo | |\n", file, sym
    }
  ' "$tmp_prev" "$tmp_symbols"
} > "$tmp_out"

mv "$tmp_out" "$out"
echo "wrote $out ($(wc -l < "$tmp_symbols" | xargs) symbols)"
