#!/usr/bin/env bash
# Regenerate PARITY.md: one row per public function in rustychickpeas-core,
# preserving the go symbol / status / notes columns of existing rows so the
# checklist survives regeneration as the Rust side keeps moving.
#
# Usage: scripts/parity.sh [path-to-rustychickpeas]   (default: ../rustychickpeas)
set -euo pipefail

rust_repo="${1:-../rustychickpeas}"
core="$rust_repo/rustychickpeas-core/src"
out="PARITY.md"

if [[ ! -d "$core" ]]; then
  echo "rustychickpeas-core not found at $core" >&2
  exit 1
fi

# "file<TAB>symbol" pairs for every pub fn outside test code.
symbols=$(grep -rn --include='*.rs' -E '^\s*pub (async )?fn [a-z_0-9]+' "$core" \
  | grep -v '/tests\.rs' \
  | sed -E "s|^$core/||; s|:[0-9]+:[[:space:]]*pub (async )?fn ([a-z_0-9]+).*|	\2|" \
  | sort -u)

prior=""
if [[ -f "$out" ]]; then
  prior=$(cat "$out")
fi

{
  echo "# Parity checklist"
  echo
  echo "Generated by scripts/parity.sh from rustychickpeas-core's public functions."
  echo "Statuses: todo / done / wontport (with a reason in notes)."
  echo
  echo "| file | rust symbol | go symbol | status | notes |"
  echo "|------|-------------|-----------|--------|-------|"
  awk -F'\t' -v prior="$prior" '
    BEGIN {
      # Index existing rows by "file|symbol" so regeneration keeps progress.
      n = split(prior, lines, "\n")
      for (i = 1; i <= n; i++) {
        line = lines[i]
        if (line !~ /^\|/) continue
        split(line, cells, "|")
        file = trim(cells[2]); sym = trim(cells[3])
        if (file == "file" || file ~ /^-+$/ || file == "") continue
        kept[file "|" sym] = line
      }
    }
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    {
      key = $1 "|" $2
      if (key in kept) print kept[key]
      else printf "| %s | %s | | todo | |\n", $1, $2
    }
  ' <<< "$symbols"
} > "$out"

echo "wrote $out ($(echo "$symbols" | wc -l | xargs) symbols)"
